export interface Artwork {
  id: number;
  title: string;
  artistName: string;
  artistAge: number;
  location: string;
  artistAvatar: string;
  artistStory: string;
  dream: string;
  description: string;
  tag: string;
  image: string;
  year: string;
  material: string;
  donorCount: number;
}

export const artworks: Artwork[] = [
  {
    id: 1,
    title: "Mặt Trời Của Em",
    artistName: "Bé Mai",
    artistAge: 6,
    location: "Quảng Ngãi",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Mai sinh ra trong một gia đình khó khăn tại vùng cao Trà Bồng. Hàng ngày em giúp mẹ nhặt củi, hái măng. Bức vẽ của em là ước mong về những ngày mùa đông ấm áp, không còn rét buốt.",
    dream: "Em muốn vẽ ông mặt trời thật to để sưởi ấm cho tất cả mọi người vào mùa đông và dẫn lối cho em tới lớp học vẽ.",
    description: "Tác phẩm thể hiện những nét vẽ mộc mạc nhưng rực rỡ sắc ấm của tông màu vàng, đỏ. Nụ cười của mặt trời xua đi cái giá lạnh của bản làng.",
    tag: "Ước mơ",
    image: "/artworks/artwork_1.png",
    year: "2024",
    material: "Sáp màu trên giấy vẽ",
    donorCount: 42,
  },
  {
    id: 2,
    title: "Xóm Nhỏ Yên Bình",
    artistName: "Minh Khôi",
    artistAge: 8,
    location: "Hà Giang",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuA1vQjWlfz4SfRIUktGDTmPxXDnH7HnuFk5XDzXXVyWw9hOd73Q5M1SPlWbPavS91ypcPojmIGwwv0eZMZuWolBxazENnc4SqIo2XI2uky1iKJlhDaTNXXne_TeLJJOUSDE7UwsIaD1X1nrKO7CEvjrE0VRIdUNhVBgWAfcTzWFboysXYug5Z5t7q0GfqHkNKqnYS8RplEBrccD87CnZ0uHJ-PhSMvhxk8w3cL9bBF7o1LD6GveLmjtbldVWueL7RuxFy2nQcJR1A7h",
    artistStory: "Khôi sống cùng ông bà trong ngôi nhà sàn đơn sơ bên sườn núi đá. Hàng ngày sau giờ học, Khôi chăn trâu trên thảo nguyên đầy hoa và cỏ dại.",
    dream: "Ước mơ của em là bản làng luôn tràn ngập màu xanh của rừng cây, có nguồn nước sạch dồi dào chảy quanh năm cho mọi người uống.",
    description: "Bức vẽ phác họa những ngôi nhà sàn giản dị ẩn hiện bên rặng cây xanh, với dòng suối mát lành uốn lượn xung quanh cảnh núi non trập trùng.",
    tag: "Thiên nhiên",
    image: "/artworks/artwork_2.png",
    year: "2024",
    material: "Sáp màu trên giấy vẽ",
    donorCount: 56,
  },
  {
    id: 3,
    title: "Gia Đình Hạnh Phúc",
    artistName: "Bé Na",
    artistAge: 5,
    location: "Cao Bằng",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Mẹ Na đi làm ăn xa, Na ở nhà cùng bố và em trai nhỏ. Dù vắng bóng mẹ thường xuyên, căn nhà nhỏ của bố con vẫn luôn rộn vang tiếng hát vui tươi.",
    dream: "Em muốn vẽ cả nhà mình có ba, mẹ, em và em trai bên mâm cơm ấm cúng lúc nào cũng tràn ngập tiếng cười hạnh phúc.",
    description: "Tác phẩm naïve đáng yêu vẽ bố mẹ và các em nắm tay nhau dưới mái nhà nhiều màu sắc rực rỡ, biểu thị khát vọng về gia đình trọn vẹn.",
    tag: "Gia đình",
    image: "/artworks/artwork_3.png",
    year: "2024",
    material: "Màu nước trên giấy",
    donorCount: 78,
  },
  {
    id: 4,
    title: "Em Làm Khoa Học",
    artistName: "Khánh An",
    artistAge: 10,
    location: "Lào Cai",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuA1vQjWlfz4SfRIUktGDTmPxXDnH7HnuFk5XDzXXVyWw9hOd73Q5M1SPlWbPavS91ypcPojmIGwwv0eZMZuWolBxazENnc4SqIo2XI2uky1iKJlhDaTNXXne_TeLJJOUSDE7UwsIaD1X1nrKO7CEvjrE0VRIdUNhVBgWAfcTzWFboysXYug5Z5t7q0GfqHkNKqnYS8RplEBrccD87CnZ0uHJ-PhSMvhxk8w3cL9bBF7o1LD6GveLmjtbldVWueL7RuxFy2nQcJR1A7h",
    artistStory: "An rất ham học hỏi, thích quan sát các chòm sao qua kẽ mái ngói thủng mỗi đêm. Em luôn ước mơ chế tạo ra kính viễn vọng để nhìn xa hơn vào khoảng không vũ trụ vô tận.",
    dream: "Sau này lớn lên em muốn trở thành phi hành gia hoặc nhà thiên văn học để được du hành và khám phá những hành tinh xa xôi.",
    description: "Nét vẽ hiện đại, đầy trí tưởng tượng phóng khoáng với phi thuyền, phi hành gia lơ lửng và những tinh vân rực rỡ đầy màu sắc nhiệm màu.",
    tag: "Ước mơ",
    image: "/artworks/artwork_4.png",
    year: "2024",
    material: "Bút màu dạ và sáp dầu",
    donorCount: 88,
  },
  {
    id: 5,
    title: "Mái Trường Mến Yêu",
    artistName: "Tùng Lâm",
    artistAge: 7,
    location: "Yên Bái",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuA1vQjWlfz4SfRIUktGDTmPxXDnH7HnuFk5XDzXXVyWw9hOd73Q5M1SPlWbPavS91ypcPojmIGwwv0eZMZuWolBxazENnc4SqIo2XI2uky1iKJlhDaTNXXne_TeLJJOUSDE7UwsIaD1X1nrKO7CEvjrE0VRIdUNhVBgWAfcTzWFboysXYug5Z5t7q0GfqHkNKqnYS8RplEBrccD87CnZ0uHJ-PhSMvhxk8w3cL9bBF7o1LD6GveLmjtbldVWueL7RuxFy2nQcJR1A7h",
    artistStory: "Lớp học của Lâm bị tốc mái sau cơn bão lớn năm trước. Dù phải học tạm trong nhà văn hóa thôn chật chội, Lâm và các bạn chưa bao giờ nghỉ buổi học nào.",
    dream: "Em ước trường học mới của bản em xây xong thật nhanh, sơn màu hồng thật đẹp để chúng em được học và vui chơi cùng nhau.",
    description: "Khung cảnh lớp học mơ ước với những ô cửa sổ lớn, những khóm hoa xinh xung quanh và hình ảnh cô giáo hiền từ đón học sinh vào lớp.",
    tag: "Trường học",
    image: "/artworks/artwork_5.png",
    year: "2024",
    material: "Sáp màu trên giấy vẽ",
    donorCount: 35,
  },
  {
    id: 6,
    title: "Biển Chiều Mơ Mộng",
    artistName: "Linh Chi",
    artistAge: 9,
    location: "Sơn La",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Chi chưa bao giờ được nhìn thấy biển ngoài đời thực vì em sinh ra ở vùng thung lũng sâu Sơn La. Em chỉ biết biển qua lời kể của thầy cô giáo và sách giáo khoa.",
    dream: "Em ước mơ một lần được đặt chân tới bãi biển thật rộng, xây lâu đài cát và ngắm đoàn thuyền đánh cá trở về trong buổi chiều hoàng hôn.",
    description: "Bức tranh vẽ những dải sóng xanh dạt dào, cánh buồm trắng xa khơi lấp lánh dưới ánh chiều tà và bầu trời nhuốm sắc hồng cam huyền diệu.",
    tag: "Thiên nhiên",
    image: "/artworks/artwork_6.png",
    year: "2024",
    material: "Bút lông màu nước",
    donorCount: 62,
  },
  {
    id: 7,
    title: "Mái Trường Cầu Vồng",
    artistName: "Lan Anh",
    artistAge: 6,
    location: "Điện Biên",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Lan Anh mỗi ngày đi bộ 5 cây số vượt dốc cao để tới trường. Dù vất vả nhưng lúc nào đôi mắt bé nhỏ cũng ngập tràn khát vọng được biết thêm chữ.",
    dream: "Em muốn vẽ trường tiểu học của em rực rỡ bảy màu cầu vồng để ngày nào đi học chúng em cũng thấy rộn ràng niềm vui thích.",
    description: "Tác phẩm sử dụng những mảng màu tương phản mạnh mẽ vẽ nên mái trường đầy sắc cầu vồng sinh động cùng những bạn nhỏ nô đùa trên sân cỏ xanh mướt.",
    tag: "Trường học",
    image: "/artworks/artwork_7.png",
    year: "2024",
    material: "Màu nước và sáp dầu",
    donorCount: 94,
  },
  {
    id: 8,
    title: "Đại Dương Kỳ Diệu",
    artistName: "Duy Mạnh",
    artistAge: 8,
    location: "Lai Châu",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuA1vQjWlfz4SfRIUktGDTmPxXDnH7HnuFk5XDzXXVyWw9hOd73Q5M1SPlWbPavS91ypcPojmIGwwv0eZMZuWolBxazENnc4SqIo2XI2uky1iKJlhDaTNXXne_TeLJJOUSDE7UwsIaD1X1nrKO7CEvjrE0VRIdUNhVBgWAfcTzWFboysXYug5Z5t7q0GfqHkNKqnYS8RplEBrccD87CnZ0uHJ-PhSMvhxk8w3cL9bBF7o1LD6GveLmjtbldVWueL7RuxFy2nQcJR1A7h",
    artistStory: "Mạnh mồ côi cha mẹ từ nhỏ, hiện sống chung với bác ruột làm nông nghèo. Mạnh là cậu bé thông minh, giàu tình cảm và rất yêu quý các động vật đại dương.",
    dream: "Ước mơ của em là được du ngoạn dưới lòng biển sâu, kết bạn với cá heo và chú rùa biển khổng lồ.",
    description: "Một thế giới nước kỳ vĩ được phác thảo tinh tế với vô vàn loài cá nhiều màu sắc bơi lượn quanh rặng san hô lấp lánh dưới biển sâu thẳm.",
    tag: "Thiên nhiên",
    image: "/artworks/artwork_8.png",
    year: "2024",
    material: "Bút chì màu và sáp dầu",
    donorCount: 110,
  },
  {
    id: 9,
    title: "Khu Rừng Biết Hát",
    artistName: "Thảo My",
    artistAge: 9,
    location: "Tuyên Quang",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Thảo My rất nhút nhát và sợ giao tiếp, nhưng em tìm thấy thế giới bình yên của mình thông qua tiếng hót của chim muông trong rừng cây sau nhà.",
    dream: "Em muốn vẽ một khu rừng cổ tích với ngàn chú chim đua nhau ca hát líu lo đón chào bình minh tươi sáng rạng ngời.",
    description: "Bức tranh sử dụng tông màu xanh lá mát dịu điểm xuyết sắc hoa rực rỡ, vẽ nhiều loài chim muông ca hát nhảy nhót vui nhộn trên cành cây.",
    tag: "Thiên nhiên",
    image: "/artworks/artwork_9.png",
    year: "2024",
    material: "Sáp màu và bút lông dạ",
    donorCount: 52,
  },
  {
    id: 10,
    title: "Ước Mơ Dưới Ánh Mặt Trời",
    artistName: "Bé Minh Quân",
    artistAge: 7,
    location: "Quảng Ngãi",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuA1vQjWlfz4SfRIUktGDTmPxXDnH7HnuFk5XDzXXVyWw9hOd73Q5M1SPlWbPavS91ypcPojmIGwwv0eZMZuWolBxazENnc4SqIo2XI2uky1iKJlhDaTNXXne_TeLJJOUSDE7UwsIaD1X1nrKO7CEvjrE0VRIdUNhVBgWAfcTzWFboysXYug5Z5t7q0GfqHkNKqnYS8RplEBrccD87CnZ0uHJ-PhSMvhxk8w3cL9bBF7o1LD6GveLmjtbldVWueL7RuxFy2nQcJR1A7h",
    artistStory: "Minh Quân sinh ra trong một gia đình thuần nông tại vùng cao Quảng Ngãi. Cuộc sống của em gắn liền với những buổi chiều cùng bà ra đồng ngắm nhìn ánh mặt trời lặn sau dãy núi nhấp nhô.",
    dream: "Em muốn trở thành một phi công để có thể bay cao thật cao, vượt qua những ngọn núi sau nhà để nhìn thấy thành phố rực rỡ ánh đèn.",
    description: "Nét vẽ đầy bản năng tái hiện ánh mặt trời khổng lồ, những đám mây trắng phau và khát vọng vươn xa của cậu bé chưa bao giờ rời bản làng.",
    tag: "Ước mơ",
    image: "/artworks/artwork_10.png",
    year: "2024",
    material: "Sáp màu trên giấy vẽ",
    donorCount: 124,
  },
];
