export interface Artwork {
  id: number;
  title: string;
  artistName: string;
  artistAge: number;
  location: string;
  artistAvatar: string;
  artistStory: string;
  dream: string;
  description: string;
  tag: string;
  image: string;
  year: string;
  material: string;
  donorCount: number;
}

export const artworks: Artwork[] = [
  {
    id: 1,
    title: "Ngôi Sao Hy Vọng",
    artistName: "Nghiêm Thị Phương Thảo",
    artistAge: 11,
    location: "Sơn La",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Giữa trang giấy trắng là một ngôi sao đỏ thật lớn, nổi bật và rực rỡ. Hai bên là những chú gà nhỏ với nét vẽ ngây ngô nhưng đầy chân thành. Có thể với người lớn, đây chỉ là những hình vẽ đơn giản. Nhưng với em, đó là cả một thế giới cảm xúc được gửi gắm bằng những nét bút mộc mạc nhất.",
    dream: "Ngôi sao đỏ ở trung tâm như một biểu tượng của niềm tự hào, của những điều đẹp đẽ mà em luôn hướng tới. Mỗi nét vẽ vụng về ấy chứa đựng sự hồn nhiên và khao khát được yêu thương.",
    description: "Khi ngắm nhìn bức tranh này, chúng ta thấy được sự cố gắng, sáng tạo và thế giới nội tâm trong trẻo của một em nhỏ khuyết tật đang dùng nghệ thuật để kể cho mọi người nghe về những điều em yêu quý. Chỉ cần dành một chút thời gian lắng nghe, chúng ta sẽ thấy trong những gam màu giản dị ấy luôn có những ước mơ rất đẹp.",
    tag: "Hy vọng",
    image: "/artworks/artwork_1.png",
    year: "2024",
    material: "Sáp màu trên giấy vẽ",
    donorCount: 42,
  },
  {
    id: 2,
    title: "Tự Hào Việt Nam",
    artistName: "Nguyễn Cao Phong",
    artistAge: 16,
    location: "Hà Giang",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuA1vQjWlfz4SfRIUktGDTmPxXDnH7HnuFk5XDzXXVyWw9hOd73Q5M1SPlWbPavS91ypcPojmIGwwv0eZMZuWolBxazENnc4SqIo2XI2uky1iKJlhDaTNXXne_TeLJJOUSDE7UwsIaD1X1nrKO7CEvjrE0VRIdUNhVBgWAfcTzWFboysXYug5Z5t7q0GfqHkNKqnYS8RplEBrccD87CnZ0uHJ-PhSMvhxk8w3cL9bBF7o1LD6GveLmjtbldVWueL7RuxFy2nQcJR1A7h",
    artistStory: "Lá cờ đỏ sao vàng được đặt ở vị trí trung tâm, nổi bật nhất trên trang giấy. Xung quanh là những trái tim xanh, ánh mặt trời rực rỡ, ngôi nhà nhỏ và những nét vẽ đầy màu sắc. Tất cả kết hợp lại như một câu chuyện giản dị nhưng chứa đựng rất nhiều yêu thương.",
    dream: "Đất nước hiện lên qua lá cờ thân thuộc, qua mái nhà bình yên, qua ánh nắng ấm áp mỗi ngày và qua những tình cảm chân thành mà em dành cho mọi người xung quanh.",
    description: "Những trái tim xuất hiện nhiều lần trong tranh như thay lời muốn nói về một trái tim luôn biết yêu thương và trân trọng những điều tốt đẹp. Bức tranh phản ánh khát vọng của mọi đứa trẻ - được sống trong bình yên, được yêu thương và tự hào về nơi mình sinh ra.",
    tag: "Tự hào",
    image: "/artworks/artwork_2.png",
    year: "2024",
    material: "Sáp màu trên giấy vẽ",
    donorCount: 56,
  },
  {
    id: 3,
    title: "Mái Nhà Bình Yên",
    artistName: "Hà Quỳnh Chi",
    artistAge: 16,
    location: "Cao Bằng",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Bức tranh của Chi mang đến cảm giác nhẹ nhàng và ấm áp ngay từ cái nhìn đầu tiên. Trên trang giấy trắng là một ngôi nhà nhỏ với mái xanh, tường cam rực rỡ và bên cạnh là một chú chó đáng yêu đang ngồi ngoan ngoãn. Từng hình ảnh đều như đang kể một câu chuyện rất riêng.",
    dream: "Ngôi nhà hiện lên với những gam màu tươi sáng, như một biểu tượng của sự an toàn và yêu thương. Đó có thể là nơi em được chăm sóc, được lắng nghe và được là chính mình.",
    description: "Hình ảnh chú chó nhỏ với khuôn mặt vui vẻ giống như một người bạn thân thiết luôn ở bên cạnh em, mang đến niềm vui, sự đồng hành vô điều kiện. Qua những nét bút giản dị, Chi đã vẽ nên một thế giới nhỏ bé nhưng đầy đủ những điều quý giá nhất: một mái nhà để trở về và một người bạn để yêu thương.",
    tag: "Gia đình",
    image: "/artworks/artwork_3.png",
    year: "2024",
    material: "Màu nước trên giấy",
    donorCount: 78,
  },
  {
    id: 4,
    title: "Bàn Tay Che Chở",
    artistName: "Trịnh Ngọc Huy",
    artistAge: 15,
    location: "Lào Cai",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Bức tranh gây ấn tượng ngay từ ánh nhìn đầu tiên bởi hình ảnh một bàn tay màu cam thật lớn ở giữa trang giấy. Xung quanh bàn tay là lá cờ đỏ sao vàng, những hình người nhỏ bé và một công trình được tô màu đen. Bức tranh mang đến nhiều cảm xúc về sự bảo vệ, yêu thương và tự hào.",
    dream: "Bàn tay lớn ở trung tâm giống như một vòng tay che chở, ôm lấy mọi điều quan trọng trong thế giới của em. So với những nhân vật nhỏ xung quanh, bàn tay hiện lên mạnh mẽ và vững chãi.",
    description: "Những hình người nhỏ bé được vẽ trong tranh chính là những người thân trong gia đình, bạn bè. Tất cả đều hiện diện dưới sự bao bọc của bàn tay lớn, tạo nên cảm giác bình yên và được chở che, gửi gắm một thông điệp rất đẹp: ai cũng cần một bàn tay nâng đỡ và một nơi để cảm thấy an toàn.",
    tag: "Yêu thương",
    image: "/artworks/artwork_4.png",
    year: "2024",
    material: "Bút màu dạ và sáp dầu",
    donorCount: 88,
  },
  {
    id: 5,
    title: "Hướng Dương Đón Nắng",
    artistName: "Hoàng Ngọc Tú",
    artistAge: 17,
    location: "Yên Bái",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Trong bức tranh của Tú, hình ảnh một bông hoa hướng dương thật lớn đang vươn mình đón nắng. Phía trên là ông mặt trời với nụ cười rạng rỡ, như đang dịu dàng nhìn ngắm mọi thứ xung quanh. Bên dưới là một ngôi nhà nhỏ, một cái cây xanh và lá cờ đỏ sao vàng tung bay.",
    dream: "Tú đã tô màu theo cách riêng: lá hoa màu đỏ, nhụy hoa màu xanh. Sự khác lạ ấy lại khiến bức tranh trở nên đặc biệt, vẽ nên từ trí tưởng tượng và cảm xúc thuần khiết nhất.",
    description: "Nhìn bức tranh này, chúng ta có thể cảm nhận được một điều rất giản dị: Tú đang nhìn cuộc sống bằng sự vui vẻ và tin yêu. Một bông hoa lớn, một mái nhà bình yên, ánh mặt trời ấm áp – nhắc chúng ta rằng hạnh phúc đôi khi chỉ đến từ những điều rất nhỏ bé.",
    tag: "Thiên nhiên",
    image: "/artworks/artwork_5.png",
    year: "2024",
    material: "Sáp màu trên giấy vẽ",
    donorCount: 35,
  },
  {
    id: 6,
    title: "Trái Tim Yêu Thương",
    artistName: "Hà Kim Anh",
    artistAge: 15,
    location: "Lai Châu",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Bức tranh của Kim Anh khiến người xem chú ý ngay từ cái nhìn đầu tiên bởi một trái tim thật lớn được đặt ở chính giữa trang giấy. Không có nhiều chi tiết cầu kỳ, Kim Anh đã chọn vẽ điều quan trọng nhất với mình: một trái tim ngập tràn yêu thương.",
    dream: "Bên trong trái tim ấy là rất nhiều nét màu đỏ được tô kín bằng sự chăm chút và kiên nhẫn. Xen giữa là những mảng màu xanh lá, xanh dương đại diện cho cây cối, bầu trời và mặt đất.",
    description: "Điều đặc biệt ở bức tranh không nằm ở kỹ thuật vẽ, mà nằm ở cảm xúc mang lại. Một trái tim lớn như muốn nói rằng trong thế giới của Kim Anh luôn có chỗ cho sự yêu thương và cho những người em quý mến. Trẻ em luôn có cách thể hiện tình cảm thật giản đơn nhưng sâu sắc.",
    tag: "Yêu thương",
    image: "/artworks/artwork_6.png",
    year: "2024",
    material: "Bút lông màu nước",
    donorCount: 62,
  },
  {
    id: 7,
    title: "Thế Giới Sắc Đỏ",
    artistName: "Hoàng Ngọc Chiến",
    artistAge: 12,
    location: "Điện Biên",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuA1vQjWlfz4SfRIUktGDTmPxXDnH7HnuFk5XDzXXVyWw9hOd73Q5M1SPlWbPavS91ypcPojmIGwwv0eZMZuWolBxazENnc4SqIo2XI2uky1iKJlhDaTNXXne_TeLJJOUSDE7UwsIaD1X1nrKO7CEvjrE0VRIdUNhVBgWAfcTzWFboysXYug5Z5t7q0GfqHkNKqnYS8RplEBrccD87CnZ0uHJ-PhSMvhxk8w3cL9bBF7o1LD6GveLmjtbldVWueL7RuxFy2nQcJR1A7h",
    artistStory: "Trong bức tranh của Chiến, màu đỏ xuất hiện ở khắp nơi. Bông hoa đỏ, chiếc cột đỏ và cả những nét màu được tô thật đậm như thể đó là màu sắc mà em yêu thích nhất. Chiến chỉ đơn giản vẽ theo những gì mình muốn và tô bằng những màu khiến em vui.",
    dream: "Ở góc tranh là những nét chì còn dang dở, cho thấy sự tự do kể câu chuyện của mình trên trang giấy bằng những nét vẽ hồn nhiên nhất. Những mảng màu lem nhẹ hay đường vẽ vụng về lại chính là dấu vết của sự tập trung.",
    description: "Bức tranh đưa chúng ta trở về tuổi thơ, khi một tờ giấy trắng và vài hộp màu đã đủ để tạo nên cả thế giới. Thế giới không cần hoàn hảo, chỉ cần có trí tưởng tượng và niềm vui mộc mạc khi được tự do thể hiện bản thân.",
    tag: "Ước mơ",
    image: "/artworks/artwork_7.png",
    year: "2024",
    material: "Màu nước và sáp dầu",
    donorCount: 94,
  },
  {
    id: 8,
    title: "Bàn Tay Sắc Màu",
    artistName: "Lý Thị Huệ",
    artistAge: 17,
    location: "Tuyên Quang",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Ý tưởng quá đỗi thương yêu và sáng tạo: biểu tượng trung tâm chính là bàn tay của em đặt lên vẽ với lòng bàn tay ấm áp mang nhiều màu sắc. Qua góc nhìn hồn nhiên, mỗi ngón tay như đại diện cho một cá tính, cùng chung sống hòa thuận và vui vẻ trên bàn tay gắn kết.",
    dream: "Bao bọc lấy bàn tay ấy là những trái tim đỏ thắm lớn nhỏ đang bay lượn tự do, tạo nên một không gian ngập tràn năng lượng tích cực. Đây chính là ước mơ mộc mạc của em về một thế giới đầy yêu thương.",
    description: "Nét sáp màu có chỗ đậm chỗ nhạt, lem viền một cách bản năng biểu thị một tâm hồn tự do. Huệ đã gửi gắm khát vọng dùng đôi bàn tay ấm áp của mình để chạm vào thế giới, để sẻ chia và lan tỏa yêu thương tới mọi người xung quanh.",
    tag: "Ước mơ",
    image: "/artworks/artwork_8.png",
    year: "2024",
    material: "Bút chì màu và sáp dầu",
    donorCount: 110,
  },
  {
    id: 9,
    title: "Tổ Ấm Bình Yên",
    artistName: "Hoàng Thị Huế",
    artistAge: 17,
    location: "Quảng Ngãi",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Ngôi nhà tường vàng mái đỏ hiện lên thật vững chãi và sống động, không chỉ là nơi che mưa che nắng mà dường như còn là biểu tượng của một tổ ấm ngập tràn niềm vui. Không gian sống ấy thật hài hòa, được ôm ấp bởi hình ảnh một cây trĩu quả và hàng cỏ hoa đón nắng.",
    dream: "Mỗi chi tiết đều được Huế vẽ theo cách rất riêng. Không có quy tắc hay khuôn mẫu nào, Huế chỉ vẽ những điều khiến em cảm thấy hạnh phúc: mái nhà bình yên, cây cối trĩu quả, lá cờ Tổ quốc dưới bầu trời đầy nắng.",
    description: "Qua nét vẽ mộc mạc của Huế, chúng ta nhận ra hạnh phúc đôi khi thật giản dị. Với một đứa trẻ, hạnh phúc có thể chỉ là một ngôi nhà thân quen, một ngày nhiều nắng và những người yêu thương luôn ở bên cạnh.",
    tag: "Gia đình",
    image: "/artworks/artwork_9.png",
    year: "2024",
    material: "Sáp màu và bút lông dạ",
    donorCount: 52,
  },
  {
    id: 10,
    title: "Mái Nhà Ước Mơ",
    artistName: "Lê Ngọc Mai",
    artistAge: 12,
    location: "Quảng Ngãi",
    artistAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPHGbiNZCEUZ8Aj6_NUErslUIeEtDrHAgzR_SmT9Np9ffz6WLSUoN9bJaIcG_8CAhEOIsqn15gGNZohSYNgYzw4tbrTjaIaAM2xDISkHEB4yx0Rvg6aRj85MGB0TdQtGuiT01jel90ETSGRP8iAvMvsR2ktC088Z-VQtdkyKERVgiplXDzz8gjeSXgyr6Zl6-dK27Px-FY1m8YYXnb8mu3A0j3u7bksfc8KbukuDkwJ-7Zv6h4KJbYplNl9OwZtTN7ooL6lBo3PxpY",
    artistStory: "Bức tranh em vẽ không chỉ là một ngôi nhà, mà là cả một ước mơ về sự bình yên và hạnh phúc của em. Ngôi nhà vươn cao với mái màu xanh da trời, đứng vững chãi giữa đất trời giống như một tổ ấm che chở cho em trước mọi giông bão.",
    dream: "Thế giới của em là một không gian ấm áp từ sắc tường vàng, nơi tình yêu thương luôn hiện hữu qua khung cửa nhỏ nhắn, bao quanh bởi tán cây trĩu quả, bầu trời xanh và tia nắng ấm áp của mặt trời rực rỡ.",
    description: "Ngọc Mai tô màu rất tự nhiên, đường vẽ tuy còn vụng về và ngây ngô nhưng lại làm cho bức tranh trở nên vô cùng đáng yêu. Mỗi nét vẽ đều kể câu chuyện riêng về những ước mơ nhỏ bé của tuổi thơ.",
    tag: "Ước mơ",
    image: "/artworks/artwork_10.png",
    year: "2024",
    material: "Sáp màu trên giấy vẽ",
    donorCount: 124,
  },
];
